# 1. Site settings
theme: jekyll-theme-minimal
logo: "/assets/logos/HS2.jpg"
title: "M. Rayan Barhdadi"
author: "M. Rayan Barhdadi"
email: "rayan.barhdadi@tamu.edu"
google_analytics: "UA-167616887-1"

# 2. Collection
collections:
  posts:
    output: true

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/rayanbarhdadi/
